### ISSUE TITLE
Install_dependencies throws error

### ISSUE THREAD

**Issue by chromadesign** [TartanLlama/actions-eleventy#4]
Hi,

When using the install_dependencies option, it throws an error on build: "##[warning]Unexpected input 'install_dependencies', valid inputs are ['entryPoint', 'args']". What can I do to make this work?

Thanks,
Manuela

**Comment by chromadesign** [comment]
The job also fails about 80% of the time with error "##[error]Docker build failed with exit code 1" for your action unfortunately...

**Comment by mahemoff** [comment]
Getting same error "Unexpected input 'install_dependencies', valid inputs are ['entryPoint', 'args']". Not sure why this was closed.

**Comment by mahemoff** [comment]
Possibly a generic Github bug due a recent change in the runner https://github.com/octokit/request-action/issues/26

**Comment by mahemoff** [comment]
Some forks are always running `npm install`, ignoring the argument, so I fixed this by switching to one of them. i.e., in `.github/workflows/eleventy_build.yml`, I simply replaced `TartanLlama/actions-eleventy@v1.1` with `mfyz/actions-eleventy@master` and now it builds.

**Comment by nielsbom** [comment]
FYI: I (still) get `Unexpected input 'install_dependencies', valid inputs are ['entryPoint', 'args']"` when using that flag.
